### ISSUE TITLE
Failed to add dependency on unit

### ISSUE THREAD

**Issue by svein** [rocky-linux/rocky-tools#10]
After running the script I as someone else also got:
```
Ensuring rpm, yum, and wget are here.
Ensuring your version of CentOS is supported
Finding our modules that are enabled

There are some modules that are unsure of how to handle. This normally shouldn't happen. Do you want to resolve this yourself (Yes) or continue (No)?
```
Without any clue to which module it was, not in the output and not in the logs. After continuing I got one error:
`Failed to add dependency on unit, unit systemd-ask-password-plymouth.service does not exist.`

The script finished successfully.

**Comment by pajamian** [comment]
centos2rocky has been deprecated in favor of migrate2rocky.  Please try again with migrate2rocky and see if your issue is resolved.

**Comment by svein** [comment]
yes, migrate2rocky fixed this issue.
