### ISSUE TITLE
Apache httpd md module not working because of wrong selinux context

### ISSUE THREAD

**Issue by aminvakil** [rocky-linux/rocky-tools#101]
After migration to Rocky Linux on a server which uses md module of httpd, `httpd` service could not be started, I investigated and reached this in `/var/log/audit/audit.log` when trying to start `httpd` service.

```
type=AVC msg=audit(1628946222.330:216): avc:  denied  { write } for  pid=2168 comm="httpd" name="example.org" dev="sda1" ino=46137569 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=dir permissive=0
```
```
find / -xdev -inum 46137569
```
returns: `/etc/httpd/md/domains/example.org`
Also
```
ll /etc/httpd/md/domains/ -Z
total 0
drwx------. 2 root root system_u:object_r:httpd_config_t:s0 75 Aug  8 03:27 example.org
```

**Comment by aminvakil** [comment]
I've executed `restorecon -Fvr /etc/httpd/md/domains/example.org` and also relabeled whole filesystem using `touch /.autorelabel` and `reboot`.

**Comment by pajamian** [comment]
Which distro did you migrate from?  Can you confirm that this wasn't an issue on the original distro?
What do you get if you pipe the output from audit.log to audit2why?

**Comment by aminvakil** [comment]
> Which distro did you migrate from?

CentOS 8.

> Can you confirm that this wasn't an issue on the original distro?

Yes.

> What do you get if you pipe the output from audit.log to audit2why?

```
[root@hostname httpd]# cat error 
type=AVC msg=audit(1628946222.330:216): avc:  denied  { write } for  pid=2168 comm="httpd" name="example.com" dev="sda1" ino=46137569 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=dir permissive=0
[root@hostname httpd]# cat error | audit2why
type=AVC msg=audit(1628946222.330:216): avc:  denied  { write } for  pid=2168 comm="httpd" name="example.org" dev="sda1" ino=46137569 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=dir permissive=0

        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.
```

**Comment by pajamian** [comment]
Okay, I was thinking that there might be a boolean for it, but obviously not.  At this point the only thing I can think of that would have caused this is if someone used chcon to change the context of the files properly and that restorecon (or similar) somehow got run during the migration (possibly by one of the rpm scriptlets) and ended up restoring the default context to the files in question.

In this particular case the best thing is likely to use semanage to add a permanent rule for the context of the given directory, so httpd can access it.  You can alternatively add a module with audit2allow as recommended by audit2why, but that will result in httpd being able to access httpd config files as if they were static files (for display), and that's likely not what you want.

**Comment by aminvakil** [comment]
I have executed `touch /.autorelabel; reboot` several times after this server has been configured an year ago for multiple reasons and there was never a problem, I'm sure I have not executed `chcon` to change the context of this file (and even if I had it would have been relabeled to default context).

I don't know what could have caused this problem too, feel free to repoen this issue if you think it might be related to `migrate2rocky` script.

**Comment by pajamian** [comment]
It might be, but without more information on what the actual cause is, or a way to reproduce it, I honestly can't really do much.  If you get more info to that regard, then please go ahead and reopen it and let me know.

**Comment by aminvakil** [comment]
Thanks for your help!
