### ISSUE TITLE
Migration from Centos 8.4 failure during distrosync due to bind module errors

### ISSUE THREAD

**Issue by 1frederic** [rocky-linux/rocky-tools#104]
Hi!

Thanks by your great job.

I try to migrate from Centos 8.4 to Rocky 8 with the migrate2rocky script.
When i deal with a bind server, I have an error message:

Error unpacking rpm package bind-32:9.11.26-4.el8_4.x86_64
error: unpacking of archive failed on file /var/named/named.empty: cpio: chown failed - Inappropriate ioctl for device
error: bind-32:9.11.26-4.el8_4.x86_64: install failed

Can you help me?

**Comment by 1frederic** [comment]
FYI, I uninstalled bind, migrated to rocky and reinstalled bind (using the configuration I saved) and everything works fine.
I think the problem came from the symbolic links used for in our bind configuration

**Comment by pajamian** [comment]
I tend to agree since we seem to have eliminated everything else I can think of.  I'm closing this issue but if you can think of anything else that is related to it please feel free to post it here.

**Comment by 1frederic** [comment]
I upgraded a bind server whithout any symbolic link and it works. So it confirms that the problem came from the symbolic links used for in our bind configuration

**Comment by pajamian** [comment]
Great!  Thanks for the confirmation.
