### ISSUE TITLE
Can not build qemu-6.0.0 on rocky-linux 8.4

### ISSUE THREAD

**Issue by naveen126** [rocky-linux/rocky-tools#107]
TO build qemu-6.0.0, The following libraries has been install.
dnf install glib2
dnf install glib2-devel

But when run "./configure" in qemu-6.0.0 directpry, the following error turns out.
ERROR: glib-2.48 gthread-2.0 is required to compile QEMU

Could you give me some help? Maybe something is wrong.

**Comment by nazunalika** [comment]
Hello. Our community likely can help you better in our forums or mattermost. I would recommend you asking in our [mattermost](https://chat.rockylinux.org) or [forums](https://forums.rockylinux.org) and provide as much detail as possible, including relevant logs.
