### ISSUE TITLE
Error during distro-sync (CentOS Stream -> Rocky)

### ISSUE THREAD

**Issue by biankss** [rocky-linux/rocky-tools#117]
Hi, i'm trying to migrate a test machine from CentOS Stream to Rocky Linux using the tool.
I have made multiple attempts and keep getting this error:
```
Syncing packages

Last metadata expiration check: 0:00:05 ago on Tue Nov  9 12:11:06 2021.
Error: 
 Problem 1: package glibc-gconv-extra-2.28-167.el8.x86_64 requires glibc(x86-64) = 2.28-167.el8, but none of the providers can be installed
  - glibc-2.28-167.el8.x86_64 does not belong to a distupgrade repository
  - problem with installed package glibc-gconv-extra-2.28-167.el8.x86_64
 Problem 2: package glibc-gconv-extra-2.28-167.el8.i686 requires glibc-common = 2.28-167.el8, but none of the providers can be installed
  - glibc-common-2.28-167.el8.x86_64 does not belong to a distupgrade repository
  - problem with installed package glibc-gconv-extra-2.28-167.el8.i686
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Error during distro-sync.
```
I already tried to edit line #888 of migrate2rocky.sh, adding `--nobest` or `--skip-broken` after `dnf -y distro-sync`, but that didn't resolve the issue.

I can do more testing if needed.
The full log file is linked below
Thanks!
[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7511789/migrate2rocky.log)

**Comment by pajamian** [comment]
I'll check tomorrow and see if I can reproduce the issue.

**Comment by pajamian** [comment]
...in the meantime, can you show the output of: `dnf repolist all` please?

**Comment by biankss** [comment]
Here's the output of `dnf repolist all`
Before attempting migration:
```
id repo                 nome repo                                   stato
appstream               CentOS Stream 8 - AppStream                 abilitato
baseos                  CentOS Stream 8 - BaseOS                    abilitato
debuginfo               CentOS Stream 8 - Debuginfo                 disabilitato
extras                  CentOS Stream 8 - Extras                    abilitato
ha                      CentOS Stream 8 - HighAvailability          disabilitato
media-appstream         CentOS Stream 8 - Media - AppStream         disabilitato
media-baseos            CentOS Stream 8 - Media - BaseOS            disabilitato
powertools              CentOS Stream 8 - PowerTools                disabilitato
rt                      CentOS Stream 8 - RealTime                  disabilitato
```
After attempting migration:
```
id repo                  nome repo                                  stato
appstream                Rocky Linux 8 - AppStream                  abilitato
appstream-debug          Rocky Linux 8 - AppStream - Source         disabilitato
appstream-source         Rocky Linux 8 - AppStream - Source         disabilitato
baseos                   Rocky Linux 8 - BaseOS                     abilitato
baseos-debug             Rocky Linux 8 - BaseOS - Source            disabilitato
baseos-source            Rocky Linux 8 - BaseOS - Source            disabilitato
devel                    Rocky Linux 8 - Devel WARNING! FOR BUILDRO disabilitato
extras                   Rocky Linux 8 - Extras                     abilitato
ha                       Rocky Linux 8 - HighAvailability           disabilitato
ha-debug                 Rocky Linux 8 - High Availability - Source disabilitato
ha-source                Rocky Linux 8 - High Availability - Source disabilitato
media-appstream          Rocky Linux 8 - Media - AppStream          disabilitato
media-baseos             Rocky Linux 8 - Media - BaseOS             disabilitato
nfv                      Rocky Linux 8 - NFV                        disabilitato
plus                     Rocky Linux 8 - Plus                       disabilitato
powertools               Rocky Linux 8 - PowerTools                 disabilitato
powertools-debug         Rocky Linux 8 - PowerTools - Source        disabilitato
powertools-source        Rocky Linux 8 - PowerTools - Source        disabilitato
resilient-storage        Rocky Linux 8 - ResilientStorage           disabilitato
resilient-storage-debug  Rocky Linux 8 - Resilient Storage - Source disabilitato
resilient-storage-source Rocky Linux 8 - Resilient Storage - Source disabilitato
rt                       Rocky Linux 8 - Realtime                   disabilitato
```

Thanks

**Comment by pajamian** [comment]
Can you add in the following lines and run migrate2rocky again:

After line 733 add `set -x`
After line 752 add `set +x`

...then try again and share the new migrate2rocky.log file.

**Comment by biankss** [comment]
I got the same error again, here's the log:
[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7518952/migrate2rocky.log)

**Comment by pajamian** [comment]
Yes, that wasn't supposed to make it work, it just gives me additional info in the log file to help trace the problem.

I see where the issue is now, I'll work up a patch and get you to try it out.

**Comment by biankss** [comment]
Great!
Thanks

**Comment by pajamian** [comment]
Can you try this version of migrate2rocky, please?
https://github.com/pajamian/rocky-tools/blob/stream_logic/migrate2rocky/migrate2rocky.sh

**Comment by biankss** [comment]
migrate2rocky seems to run fine, but when i reboot the machine doesn't boot anymore
[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7519468/migrate2rocky.log)
.
here's the error on boot
![image](https://user-images.githubusercontent.com/79417424/141277974-3c0e36a0-bf1d-4629-a08f-8d4dbc24e4b4.png)

**Comment by pajamian** [comment]
I think I see the issue.  What happens if you follow the migration with this command before rebooting:
```
dnf distro-sync grub2-efi-x64
grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
efibootmgr -c -d "/dev/<your_boot_disk>" -p "<efi_partition_number>" -L "Rocky Linux" -l /EFI/rocky/grubx64.efi
```
...substitute the appropriate device and partition number in the command above, if you're not sure then migrate2rocky can tell you what they are:
After line 422 add the following:
```
echo "EFI device and partition data:"
declare -p efi_disk efi_partition
```
...and you'll see the device name and partition numbers in the migrate2rocky output.

**Comment by biankss** [comment]
It worked! here's [migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7520761/migrate2rocky.log)
Thanks a lot!

**Comment by pajamian** [comment]
Thanks, that confirms what I need to fix in migrate2rocky.  I may ask you to test it again once I've fixed it.

**Comment by biankss** [comment]
Ok! Thanks, let me know if you need more testing!

**Comment by pajamian** [comment]
Can you test with this?
https://github.com/rocky-linux/rocky-tools/blob/210d1fc998762352f29d99340e7ecc3288d7a111/migrate2rocky/migrate2rocky.sh

Thanks

**Comment by biankss** [comment]
It worked. Log below
[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7594078/migrate2rocky.log)

**Comment by pajamian** [comment]
Thanks for the input and testing.
