### ISSUE TITLE
Failure to migrate CentOS 8 Stream to Rocky Linux - Error during distro-sync

### ISSUE THREAD

**Issue by drees** [rocky-linux/rocky-tools#121]
Grabbed the latest migrate2rocky.sh from git and tried to upgrade a CentOS 8 Stream system to Rocky Linux which ended with "Error during distro-sync". Trying to run again ends up with error "Found a full or partial RockyLinux install already in place.

What steps next to recover?

[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/7552248/migrate2rocky.log)

**Comment by pajamian** [comment]
Hi drees,

That's actually a known issue, which we will hopefully have fixed soon.  As for how to recover from it:

As root:

```
curl http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-8-3.el8.noarch.rpm | rpm2cpio | cpio -iD/ *.repo
sed -i 's/^\[/[stream-/' /etc/yum.repos.d/CentOS-Stream-*.repo
dnf config-manager --save --setopt=stream-\*.exclude=grub2-efi\*
dnf repo-sync
dnf config-manager --disable=stream-\*
```
If your system uses EFI boot then you'll need the following steps as well:
```
grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
efibootmgr -c -d "/dev/<your_boot_disk>" -p "<efi_partition_number>" -L "Rocky Linux" -l /EFI/rocky/grubx64.efi
```
..substitute the appropriate device and partition number in the command above.

This is a lot of steps, and stuff can go wrong.  If you need additional help, please don't hesitate to ask.

**Comment by drees** [comment]
Got an error with the repo-sync command - did you mean reposync?

```
# dnf repo-sync
No such command: repo-sync. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(repo-sync)'"
# dnf reposync
CentOS Stream 8 - AppStream                                                                                       215  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'stream-appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

But now it looks like the sed command didn't quite edit the repo files properly - here's the relevant portion of the CentOS-Stream-AppStream.repo file:

```
[stream-appstream]
name=CentOS Stream $releasever - AppStream
mirrorlist=http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=AppStream&infra=$infra
#baseurl=http://mirror.centos.org/$contentdir/$stream/AppStream/$basearch/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
exclude=grub2-efi*

```

**Comment by drees** [comment]
I commented out the mirrorlist and uncommented the baseurl, got this error:
```
# dnf reposync
CentOS Stream 8 - AppStream                                                                                        19 kB/s | 8.3 kB     00:00    
Errors during downloading metadata for repository 'stream-appstream':
  - Status code: 404 for http://mirror.centos.org/pub/rocky/$stream/AppStream/x86_64/os/repodata/repomd.xml (IP: 108.61.16.227)
Error: Failed to download metadata for repo 'stream-appstream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
I'm confused as to what your steps are trying to do.
It seems like if I just uninstall the RPMs that are causing the issues and re-run dnf distro-sync that should get things going OK?

I was able to uninstall the qemu-kvm packages that were problems in the logs, but for some reason when trying to uninstall glibc-gconv-extra, it won't let me do so as it's needed by glibc - so I'm kind of afraid to force the uninstall and end up with a broken system before re-running distro-sync.

```
# rpm -e glibc-gconv-extra-2.28-167.el8.x86_64
error: Failed dependencies:
	glibc-gconv-extra(x86-64) = 2.28-167.el8 is needed by (installed) glibc-2.28-167.el8.x86_64
```

**Comment by pajamian** [comment]
> Thanks for the quick reply and help!
> 
> I got an error with the repo-sync command - did you mean reposync?

Sorry, I meant `distro-sync`

**Comment by pajamian** [comment]
> I commented out the mirrorlist and uncommented the baseurl, got this error:
> 
> ```
> # dnf reposync
> CentOS Stream 8 - AppStream                                                                                        19 kB/s | 8.3 kB     00:00    
> Errors during downloading metadata for repository 'stream-appstream':
>   - Status code: 404 for http://mirror.centos.org/pub/rocky/$stream/AppStream/x86_64/os/repodata/repomd.xml (IP: 108.61.16.227)
> Error: Failed to download metadata for repo 'stream-appstream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Try setting baseurl to: `http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/`

...and a similar baseurl for the other stream repos.  I'll come up with a sed to do it in one step but have to run out for a couple of hours first.

> I'm confused as to what your steps are trying to do. It seems like if I just uninstall the RPMs that are causing the issues and re-run dnf distro-sync that should get things going OK?

The issue is more or less explained here:
https://github.com/rocky-linux/rocky-tools/blob/main/migrate2rocky/migrate2rocky.sh#L891

**Comment by pajamian** [comment]
Try this:
`sed -e 's|^mirrorlist=|#mirrorlist=|' -e 's|^#baseurl=http://mirror.centos.org/$contentdir/$stream/|baseurl=http://mirror.centos.org/centos/8-stream/|' -i.bak /etc/yum.repos.d/CentOS-Stream-*.repo`

**Comment by drees** [comment]
OK, so I did that - but running distro-sync just wants to reinstall packages from CentOS-stream:

```
# dnf distro-sync
Last metadata expiration check: 0:03:43 ago on Thu 18 Nov 2021 06:40:54 PM PST.
Dependencies resolved.
================================================================================
 Package                      Arch   Version             Repository        Size
================================================================================
Upgrading:
 alsa-sof-firmware            noarch 1.9-1.el8           stream-baseos    693 k
 device-mapper                x86_64 8:1.02.181-1.el8    stream-baseos    377 k
 device-mapper-event          x86_64 8:1.02.181-1.el8    stream-baseos    271 k
 device-mapper-event-libs     x86_64 8:1.02.181-1.el8    stream-baseos    270 k
 device-mapper-libs           x86_64 8:1.02.181-1.el8    stream-baseos    409 k
 device-mapper-multipath      x86_64 0.8.4-19.el8        stream-baseos    198 k
 device-mapper-multipath-libs x86_64 0.8.4-19.el8        stream-baseos    323 k
 kpartx                       x86_64 0.8.4-19.el8        stream-baseos    113 k
 libstoragemgmt               x86_64 1.9.1-3.el8         stream-baseos    246 k
 lvm2                         x86_64 8:2.03.14-1.el8     stream-baseos    1.7 M
 lvm2-libs                    x86_64 8:2.03.14-1.el8     stream-baseos    1.2 M
 python3-libstoragemgmt       x86_64 1.9.1-3.el8         stream-baseos    176 k
 rsyslog                      x86_64 8.2102.0-6.el8      stream-appstream 752 k
 rsyslog-gnutls               x86_64 8.2102.0-6.el8      stream-appstream  32 k
 rsyslog-gssapi               x86_64 8.2102.0-6.el8      stream-appstream  34 k
 rsyslog-relp                 x86_64 8.2102.0-6.el8      stream-appstream  33 k
 unzip                        x86_64 6.0-45.el8_4        baseos           194 k

Transaction Summary
================================================================================
Upgrade  17 Packages

Total download size: 6.9 M
```

Isn't the goal to get the system synced w/Rocky Linux 8.5?

**Comment by pajamian** [comment]
I think those are new packages in stream since you initially started the migration.  At this stage, and based on the above output, I would skip the distro-sync and do the following steps:
```
dnf config-manager --disable=stream-\*
dnf update
```

...and if your system uses EFI boot then the following:
```
grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
efibootmgr -c -d "/dev/<your_boot_disk>" -p "<efi_partition_number>" -L "Rocky Linux" -l /EFI/rocky/grubx64.efi
```

That should hopefully fix things up for you.

**Comment by drees** [comment]
OK, that's all done - all appears to be OK except one thing, and I think it's not specific to CentOS 8 Stream to Rocky as I have this issue on another machine:

ssh password logins are failing, but ssh private key logins are working OK. Really weird, and nothing in the logs to indicate why. 

Any ideas?

Also, is there an updated script available to help people avoid this issue when migrating from Stream to Rocky?

**Comment by pajamian** [comment]
Is the migrated machine the ssh client or server?  Can you reproduce this problem with a machine that is a pure Rocky Linux install (not migrated), what about a pure CentOS Stream 8 install?  What do you get with ssh -vv output?

I'm working on the updated script now, it may still be a couple of days until I can get it finished.  Your reports and feedback have helped a great deal with it, thank you.

**Comment by drees** [comment]
The ssh server was the migrated system. The ssh client OS didn't matter.

I figured out what was causing the issue, though not sure how it got changed - /etc/pam.d/sshd was missing the line:
`auth substack password-auth`
There was a sshd.prev file in the folder, copying that over the sshd file got things working.

Thanks for your help!
