### ISSUE TITLE
Trouble running migrate2rocky.sh with package dependencies (jasper-devel)

### ISSUE THREAD

**Issue by Wahnes** [rocky-linux/rocky-tools#122]
I already ran a few migrations from CentOS to Rocky Linux that worked like a charm. So, first off, thanks for this easy to use and well working method to migrate from CentOS to Rocky Linux!

However, I had some trouble running `migrate2rocky.sh` on a box where the RPM package `jasper-devel` was installed. This was the error message I received:

```
Error:
 Problem: cannot install both jasper-libs-2.0.14-5.el8.x86_64 and jasper-libs-2.0.14-4.el8.x86_64
  - package jasper-devel-2.0.14-4.el8.x86_64 requires jasper-libs(x86-64) = 2.0.14-4.el8, but none of the providers can be installed
  - cannot install the best update candidate for package jasper-libs-2.0.14-4.el8.x86_64
  - problem with installed package jasper-devel-2.0.14-4.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

As you can see, the problem arises from the dependencies of the `jasper-devel` package. This package is tied to the corresponding version of `jasper-libs`.

The root cause could very well be that the box in question was still on CentOS 8.4 (`8.4.2105` is the nomenclature CentOS uses), so this might not be a real bug after all. I read in the documentation that one should use `migrate2rocky.sh` to migrate from 8.5 to 8.5, so this issue may be out of scope. But I figured I'd still report it, because with just the `jasper-devel` package removed, the migration from CentOS 8.4 to Rocky Linux 8.5 on the above box went just fine (including an update of `jasper-libs-2.0.14-4` to `jasper-libs-2.0.14-5`). So, I'm not sure if problems with dependencies like these could be circumvented when running `migrate2rocky.sh`. But if this is possible, it would certainly help make the migration even smoother in some situations.

**Comment by nazunalika** [comment]
I would be curious to see the logs. This almost tells me powertools wasn't enabled (which is where jasper-devel comes from), but it's hard to say what happened.

**Comment by Wahnes** [comment]
> I would be curious to see the logs.

Is there any particular part that I should post? The log file is quite long (some 12000 lines), so I'm not sure if posting all of it makes sense. As far as I can tell, the logfile contains information from the second migration attempt only (with the `jasper-devel` package already removed), which succeeded. The information gathered during the first attempt seems to have been overwritten.

**Comment by pajamian** [comment]
Indeed I would say that you have powertools disabled.  jasper-devel is in powertools while jasper-libs is in appstream (even though they're from the same source package).
It's always a good idea to enable powertools in EL8:
`dnf config-manager --set-enabled powertools`

**Comment by Wahnes** [comment]
> Indeed I would say that you have powertools disabled. 

You're right. The PowerTools repository was disabled on that box.
I don't recall disabling it (or enabling it in the first place to be able to install `jasper-devel`), but that really seems to be the cause here.
Thank you for your attention and for your insights to the issue. Sorry for the nuisance.
