### ISSUE TITLE
Failure update Rocky Linux 8.4 (migrated from centos) to 8.5

### ISSUE THREAD

**Issue by castellinosoftware** [rocky-linux/rocky-tools#123]
I have a RockyLinux 8.4 installation obtained by migrating from Centos.
When I try to upgrade to RL 8.5 the transaction is blocked by the following error:

Error: Transaction test error:
file /usr/share/pixmaps/poweredby.png from install of rocky-logos-httpd-85.0-3.el8.noarch conflicts with file from package centos-logos-httpd-85.5-1.el8.noarch
file /usr/share/testpage/index.html from install of rocky-logos-httpd-85.0-3.el8.noarch conflicts with file from package centos-logos-httpd-85.5-1.el8.noarch

I assume that the migration script should have replaced the package.

Checking my system I found
centos-logos-httpd, Version 85.5, Release :1.el8 installed
rocky-logos-httpd, Version 85.0, Release :3.el8 available

Should I unistall centos-logos-httpd-85.5-1.el8.noarch package before dnf update?

The main problem is that the removal uninstal a lot of things, like httpd and php.

Can you help me with some alternatives?

**Comment by pajamian** [comment]
Can you show the full command you're using to update and the resulting full output from dnf?

**Comment by castellinosoftware** [comment]
Hi.
I did a simple: dnf update

I attach the full output in this txt file:
[output.txt](https://github.com/rocky-linux/rocky-tools/files/7569860/output.txt)

Thank you for help

**Comment by pajamian** [comment]
There was an issue with this package being left out of the migration which has since been fixed.  Perhaps you migrated with a version of migrate2rocky from before that fix.  To fix your problem now try this:

dnf swap centos-logos-httpd rocky-logos-httpd

...then try again.  If it still fails then there are more forceful ways to fix the issue.

**Comment by castellinosoftware** [comment]
Swapping packages fix the issue.
Many thanks
