### ISSUE TITLE
migrate2rocky script failed on CentOS 8 aarch64

### ISSUE THREAD

**Issue by boegel** [rocky-linux/rocky-tools#137]
I ran into the following issue when trying to use the `migrate2rocky` script to migrate a CentOS 8 aarch64 VM to Rocky Linux:

```
    amazon-ebs.aws: No match for argument: shim-x64
    amazon-ebs.aws: No match for argument: grub2-efi-x64
==> amazon-ebs.aws: Error: Unable to find a match: shim-x64 grub2-efi-x64
==> amazon-ebs.aws:
==> amazon-ebs.aws: Error installing required packages: shim-x64 grub2-efi-x64
==> amazon-ebs.aws:
```

It looks like this issue was introduced recently with 540327a1cbaf08188921f60ca3629dfd9d417f4d

**Comment by boegel** [comment]
It looks like those packages for `aarch64` are `grub2-efi-aa64` and `shim-aa64` respectively...

I'll see if I can come up with a patch for `migrate2rocky` that works.

**Comment by pajamian** [comment]
Thanks.  A patch would be appreciated.

I would recommend using $ARCH to key an associative array that holds the package names by arch, or something to that extent.  If you want to leave it to me that's fine, but can you tell me what the output of `arch` is on your system?

**Comment by boegel** [comment]
I'm testing the follow patch: https://github.com/boegel/rocky-tools/commit/f3f1f9ae1ce327f673aed27fe1b26c50f52ad15c

**Comment by pajamian** [comment]
I gave some comments on your patch.

**Comment by boegel** [comment]
@pajamian Thanks for the feedback! I've opened a pull request taking your comments into account: #138
