### ISSUE TITLE
Error: Cannot find a valid baseurl for repo: extras

### ISSUE THREAD

**Issue by nofateyang** [rocky-linux/rocky-tools#164]
Dear All,

I have the following error with the migrate script :

![image](https://user-images.githubusercontent.com/7752841/155709666-98a76a7a-cc89-447b-a201-f80d35a511b0.png)
![image](https://user-images.githubusercontent.com/7752841/155710465-533a56e0-367c-4af9-8422-22df0f066e83.png)

[root@svr1 ~]# ./migrate2rocky.sh -r
migrate2rocky - Begin logging at Fri 25 Feb 2022 07:43:47 PM CST.

Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

Baseurl for extras is invalid, setting to .
Baseurl for AppStream is invalid, setting to .
Determining repository names for CentOS Linux 8.Error: Cannot find a valid baseurl for repo: extras

Failed to fetch info for package apr-util-ldap.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log

 [root@svr1 ~]# cat /etc/redhat-release
CentOS Linux release 8.5.2111

And not [https://github.com/rocky-linux/rocky-tools/issues/85](https://github.com/rocky-linux/rocky-tools/issues/85)

**Comment by mafgh** [comment]
This happened to me, when the machine was unable to reach the centos.org repository, due to a missing proxy configuration/firewall in place.

**Comment by nofateyang** [comment]
I switched to centos-vault bcz Centos8 EOL，so can “yum clean all  && yum makecache” OK。
FYI:  https://developer.aliyun.com/mirror/centos?spm=a2c6h.13651102.0.0.3e221b11QKtolj

wget -O /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo

_[root@svr1 ~]# ls /etc/yum.repos.d/
CentOS-Base.repo  epel-modular.repo  epel.repo  epel-testing-modular.repo  epel-testing.repo  nux-dextop.repo_

> This happened to me, when the machine was unable to reach the centos.org repository, due to a missing proxy configuration/firewall in place.

**Comment by pajamian** [comment]
migrate2rocky should have automatically switched to the vault mirror that is maintained by Rocky Linux.  Can you add `set -x` before line 609 and `set +x` before line 660, then run migrate2rocky again and copy the resulting migrate2rocky.log file here?

Thanks

**Comment by nofateyang** [comment]
> migrate2rocky should have automatically switched to the vault mirror that is maintained by Rocky Linux. Can you add `set -x` before line 609 and `set +x` before line 660, then run migrate2rocky again and copy the resulting migrate2rocky.log file here?
> 
> Thanks
![image](https://user-images.githubusercontent.com/7752841/155828652-98326d20-3e70-4a46-a6a9-8ed12bf91d5b.png)
![image](https://user-images.githubusercontent.com/7752841/155828679-4299f07e-c7c0-499b-8905-86cbc32e99e1.png)

[root@svr1 ~]# cat  /var/log/migrate2rocky.log
migrate2rocky - Begin logging at Sat 26 Feb 2022 12:21:29 PM CST.


Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

+ local -A dist_repourl_map
+ dist_repourl_map=([centos:baseos]=https://dl.rockylinux.org/vault/centos/8.5.2111/BaseOS/$ARCH/os/ [centos:appstream]=https://dl.rockylinux.org/vault/centos/8.5.2111/AppStream/$ARCH/os/ [centos:ha]=https://dl.rockylinux.org/vault/centos/8.5.2111/HighAvailability/$ARCH/os/ [centos:powertools]=https://dl.rockylinux.org/vault/centos/8.5.2111/PowerTools/$ARCH/os/ [centos:extras]=https://dl.rockylinux.org/vault/centos/8.5.2111/extras/$ARCH/os/ [centos:devel]=https://dl.rockylinux.org/vault/centos/8.5.2111/Devel/$ARCH/os/)
+ for name in BaseOS AppStream PowerTools Devel
+ dist_repourl_map["centos:$name"]=https://dl.rockylinux.org/vault/centos/8.5.2111/BaseOS/x86_64/os/
+ for name in BaseOS AppStream PowerTools Devel
+ dist_repourl_map["centos:$name"]=https://dl.rockylinux.org/vault/centos/8.5.2111/AppStream/x86_64/os/
+ for name in BaseOS AppStream PowerTools Devel
+ dist_repourl_map["centos:$name"]=https://dl.rockylinux.org/vault/centos/8.5.2111/PowerTools/x86_64/os/
+ for name in BaseOS AppStream PowerTools Devel
+ dist_repourl_map["centos:$name"]=https://dl.rockylinux.org/vault/centos/8.5.2111/Devel/x86_64/os/
+ dist_repourl_map[centos:HighAvailability]=https://dl.rockylinux.org/vault/centos/8.5.2111/HighAvailability/x86_64/os/
+ enabled_repos=()
+ local -a enabled_repos
+ enabled_repo_check=()
+ declare -g -A enabled_repo_check
+ dist_repourl_swaps=()
+ declare -g -a dist_repourl_swaps
+ readarray -s 1 -t enabled_repos
++ dnf -q -y repolist --enabled
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for r in "${enabled_repos[@]}"
+ enabled_repo_check[${r%% *}]=1
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=ha
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=PowerTools
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=extras
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n 1 ]]
+ check_repourl extras
+ repoinfo extras
+ [[ ! -n '' ]]
+ _repoinfo extras
+ local name val result
++ safednf -y -q --repo=extras repoinfo extras
++ args=()
++ for a in "$@"
++ [[ -n -y ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n -q ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --repo=extras ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n repoinfo ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n extras ]]
++ args+=("$a")
++ dnf -y -q --repo=extras repoinfo extras
+ result='Repo-id            : extras
Repo-name          : CentOS-8.5.2111 - Extras - mirrors.aliyun.com
Repo-status        : enabled
Repo-revision      : 1639140985
Repo-updated       : Fri Dec 10 20:56:25 2021
Repo-pkgs          : 38
Repo-available-pkgs: 38
Repo-size          : 426 k
Repo-baseurl       : http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/
Repo-expire        : 172800 second(s) (last: Sat Feb 26 12:21:30 2022)
Repo-filename      : /etc/yum.repos.d/CentOS-Base.repo
Total packages: 38'
+ [[ Repo-id            : extras
Repo-name          : CentOS-8.5.2111 - Extras - mirrors.aliyun.com
Repo-status        : enabled
Repo-revision      : 1639140985
Repo-updated       : Fri Dec 10 20:56:25 2021
Repo-pkgs          : 38
Repo-available-pkgs: 38
Repo-size          : 426 k
Repo-baseurl       : http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/
Repo-expire        : 172800 second(s) (last: Sat Feb 26 12:21:30 2022)
Repo-filename      : /etc/yum.repos.d/CentOS-Base.repo
Total packages: 38 == \T\o\t\a\l\ \p\a\c\k\a\g\e\s\:\ \0 ]]
+ repoinfo_results=()
+ declare -gA repoinfo_results
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-id ]]
+ [[ -z Repo-id ]]
+ prev=Repo-id
+ repoinfo_results[$name]=extras
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-name ]]
+ [[ -z Repo-name ]]
+ prev=Repo-name
+ repoinfo_results[$name]='CentOS-8.5.2111 - Extras - mirrors.aliyun.com'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-status ]]
+ [[ -z Repo-status ]]
+ prev=Repo-status
+ repoinfo_results[$name]=enabled
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-revision ]]
+ [[ -z Repo-revision ]]
+ prev=Repo-revision
+ repoinfo_results[$name]=1639140985
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-updated ]]
+ [[ -z Repo-updated ]]
+ prev=Repo-updated
+ repoinfo_results[$name]='Fri Dec 10 20:56:25 2021'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-pkgs ]]
+ [[ -z Repo-pkgs ]]
+ prev=Repo-pkgs
+ repoinfo_results[$name]=38
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-available-pkgs ]]
+ [[ -z Repo-available-pkgs ]]
+ prev=Repo-available-pkgs
+ repoinfo_results[$name]=38
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-size ]]
+ [[ -z Repo-size ]]
+ prev=Repo-size
+ repoinfo_results[$name]='426 k'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-baseurl ]]
+ [[ -z Repo-baseurl ]]
+ prev=Repo-baseurl
+ repoinfo_results[$name]='http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-expire ]]
+ [[ -z Repo-expire ]]
+ prev=Repo-expire
+ repoinfo_results[$name]='172800 second(s) (last: Sat Feb 26 12:21:30 2022)'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-filename ]]
+ [[ -z Repo-filename ]]
+ prev=Repo-filename
+ repoinfo_results[$name]=/etc/yum.repos.d/CentOS-Base.repo
+ IFS=' :'
+ read -r name val
+ [[ -n Total ]]
+ [[ -z Total ]]
+ prev=Total
+ repoinfo_results[$name]='packages: 38'
+ IFS=' :'
+ read -r name val
+ [[ ! -n 1 ]]
++ awk '
            $0=="[extras]",$0=="end_of_file" {
                if (l++ < 1) {next}
                else if (/^\[.*\]$/) {nextfile}
                else if (sub(/^gpgkey\s*=\s*file:\/\//,"")) {print; nextfile}
                else {next}
            }
        '
+ repoinfo_results[Repo-gpgkey]=
++ awk '
            BEGIN {FS="[)(]"}
            /^# Managed by \(.*\) subscription-manager$/ {print $2}
        '
+ repoinfo_results[Repo-managed]=
+ repoinfo_results_cache[$1]=1
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=38
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=enabled
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='CentOS-8.5.2111 - Extras - mirrors.aliyun.com'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='packages: 38'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='426 k'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=extras
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='Fri Dec 10 20:56:25 2021'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=/etc/yum.repos.d/CentOS-Base.repo
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=38
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=1639140985
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='172800 second(s) (last: Sat Feb 26 12:21:30 2022)'
+ [[ ! -n http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/extras/x86_64/os/ ]]
+ curl -sfLI http://mirrors.aliyun.com/centos-vault/8.5.2111/extras/x86_64/os/,repodata/repomd.xml
+ return
+ dist_repourl_swaps+=("--setopt=$r.mirrorlist=" "--setopt=$r.metalink=" "--setopt=$r.baseurl=" "--setopt=$r.baseurl=${dist_repourl_map[$k]}")
+ infomsg 'Baseurl for %s is invalid, setting to %s.\n' extras ''
+ local msg
+ msg_format msg 'Baseurl for %s is invalid, setting to %s.\n' extras ''
+ local _var
+ _var=msg
+ shift
+ ((  3 > 1  ))
+ printf -v msg 'Baseurl for %s is invalid, setting to %s.\n' extras ''
+ printf %s 'Baseurl for extras is invalid, setting to .
'
Baseurl for extras is invalid, setting to .
+ printf %s%s%s '' 'Baseurl for extras is invalid, setting to .
' ''
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=HighAvailability
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=devel
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=AppStream
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n 1 ]]
+ check_repourl AppStream
+ repoinfo AppStream
+ [[ ! -n '' ]]
+ _repoinfo AppStream
+ local name val result
++ safednf -y -q --repo=AppStream --setopt=extras.mirrorlist= --setopt=extras.metalink= --setopt=extras.baseurl= --setopt=extras.baseurl= repoinfo AppStream
++ args=()
++ for a in "$@"
++ [[ -n -y ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n -q ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --repo=AppStream ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --setopt=extras.mirrorlist= ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --setopt=extras.metalink= ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --setopt=extras.baseurl= ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n --setopt=extras.baseurl= ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n repoinfo ]]
++ args+=("$a")
++ for a in "$@"
++ [[ -n AppStream ]]
++ args+=("$a")
++ dnf -y -q --repo=AppStream --setopt=extras.mirrorlist= --setopt=extras.metalink= --setopt=extras.baseurl= --setopt=extras.baseurl= repoinfo AppStream
+ result='Repo-id            : AppStream
Repo-name          : CentOS-8.5.2111 - AppStream - mirrors.aliyun.com
Repo-status        : enabled
Repo-revision      : 8.5.2111
Repo-distro-tags      : [cpe:/o:centos:centos:8]:  , 8, C, O, S, e, n, t
Repo-updated       : Fri Dec 31 14:06:52 2021
Repo-pkgs          : 6533
Repo-available-pkgs: 5596
Repo-size          : 11 G
Repo-baseurl       : http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/
Repo-expire        : 172800 second(s) (last: Sat Feb 26 12:21:34 2022)
Repo-filename      : /etc/yum.repos.d/CentOS-Base.repo
Total packages: 6533'
+ [[ Repo-id            : AppStream
Repo-name          : CentOS-8.5.2111 - AppStream - mirrors.aliyun.com
Repo-status        : enabled
Repo-revision      : 8.5.2111
Repo-distro-tags      : [cpe:/o:centos:centos:8]:  , 8, C, O, S, e, n, t
Repo-updated       : Fri Dec 31 14:06:52 2021
Repo-pkgs          : 6533
Repo-available-pkgs: 5596
Repo-size          : 11 G
Repo-baseurl       : http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/
Repo-expire        : 172800 second(s) (last: Sat Feb 26 12:21:34 2022)
Repo-filename      : /etc/yum.repos.d/CentOS-Base.repo
Total packages: 6533 == \T\o\t\a\l\ \p\a\c\k\a\g\e\s\:\ \0 ]]
+ repoinfo_results=()
+ declare -gA repoinfo_results
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-id ]]
+ [[ -z Repo-id ]]
+ prev=Repo-id
+ repoinfo_results[$name]=AppStream
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-name ]]
+ [[ -z Repo-name ]]
+ prev=Repo-name
+ repoinfo_results[$name]='CentOS-8.5.2111 - AppStream - mirrors.aliyun.com'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-status ]]
+ [[ -z Repo-status ]]
+ prev=Repo-status
+ repoinfo_results[$name]=enabled
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-revision ]]
+ [[ -z Repo-revision ]]
+ prev=Repo-revision
+ repoinfo_results[$name]=8.5.2111
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-distro-tags ]]
+ [[ -z Repo-distro-tags ]]
+ prev=Repo-distro-tags
+ repoinfo_results[$name]='[cpe:/o:centos:centos:8]:  , 8, C, O, S, e, n, t'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-updated ]]
+ [[ -z Repo-updated ]]
+ prev=Repo-updated
+ repoinfo_results[$name]='Fri Dec 31 14:06:52 2021'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-pkgs ]]
+ [[ -z Repo-pkgs ]]
+ prev=Repo-pkgs
+ repoinfo_results[$name]=6533
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-available-pkgs ]]
+ [[ -z Repo-available-pkgs ]]
+ prev=Repo-available-pkgs
+ repoinfo_results[$name]=5596
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-size ]]
+ [[ -z Repo-size ]]
+ prev=Repo-size
+ repoinfo_results[$name]='11 G'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-baseurl ]]
+ [[ -z Repo-baseurl ]]
+ prev=Repo-baseurl
+ repoinfo_results[$name]='http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-expire ]]
+ [[ -z Repo-expire ]]
+ prev=Repo-expire
+ repoinfo_results[$name]='172800 second(s) (last: Sat Feb 26 12:21:34 2022)'
+ IFS=' :'
+ read -r name val
+ [[ -n Repo-filename ]]
+ [[ -z Repo-filename ]]
+ prev=Repo-filename
+ repoinfo_results[$name]=/etc/yum.repos.d/CentOS-Base.repo
+ IFS=' :'
+ read -r name val
+ [[ -n Total ]]
+ [[ -z Total ]]
+ prev=Total
+ repoinfo_results[$name]='packages: 6533'
+ IFS=' :'
+ read -r name val
+ [[ ! -n 1 ]]
++ awk '
            $0=="[AppStream]",$0=="end_of_file" {
                if (l++ < 1) {next}
                else if (/^\[.*\]$/) {nextfile}
                else if (sub(/^gpgkey\s*=\s*file:\/\//,"")) {print; nextfile}
                else {next}
            }
        '
+ repoinfo_results[Repo-gpgkey]=
++ awk '
            BEGIN {FS="[)(]"}
            /^# Managed by \(.*\) subscription-manager$/ {print $2}
        '
+ repoinfo_results[Repo-managed]=
+ repoinfo_results_cache[$1]=1
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=6533
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=enabled
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='CentOS-8.5.2111 - AppStream - mirrors.aliyun.com'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='packages: 6533'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='11 G'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=AppStream
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='Fri Dec 31 14:06:52 2021'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=/etc/yum.repos.d/CentOS-Base.repo
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=5596
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='[cpe:/o:centos:centos:8]:  , 8, C, O, S, e, n, t'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/'
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]=8.5.2111
+ for k in "${!repoinfo_results[@]}"
+ repoinfo_results_cache[$1:$k]='172800 second(s) (last: Sat Feb 26 12:21:34 2022)'
+ [[ ! -n http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/, http://mirrors.cloud.aliyuncs.com/centos-vault/8.5.2111/AppStream/x86_64/os/ ]]
+ curl -sfLI http://mirrors.aliyun.com/centos-vault/8.5.2111/AppStream/x86_64/os/,repodata/repomd.xml
+ return
+ dist_repourl_swaps+=("--setopt=$r.mirrorlist=" "--setopt=$r.metalink=" "--setopt=$r.baseurl=" "--setopt=$r.baseurl=${dist_repourl_map[$k]}")
+ infomsg 'Baseurl for %s is invalid, setting to %s.\n' AppStream ''
+ local msg
+ msg_format msg 'Baseurl for %s is invalid, setting to %s.\n' AppStream ''
+ local _var
+ _var=msg
+ shift
+ ((  3 > 1  ))
+ printf -v msg 'Baseurl for %s is invalid, setting to %s.\n' AppStream ''
+ printf %s 'Baseurl for AppStream is invalid, setting to .
'
Baseurl for AppStream is invalid, setting to .
+ printf %s%s%s '' 'Baseurl for AppStream is invalid, setting to .
' ''
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=BaseOS
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=appstream
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=Devel
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=baseos
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ for k in "${!dist_repourl_map[@]}"
+ local d=centos r=powertools
+ [[ centos != \c\e\n\t\o\s ]]
+ [[ ! -n '' ]]
+ continue
+ set +x
Determining repository names for CentOS Linux 8.Error: Cannot find a valid baseurl for repo: extras

Failed to fetch info for package apr-util-ldap.x86_64.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

[root@svr1 ~]#

**Comment by pajamian** [comment]
Can you try this version of migrate2rocky please?
https://raw.githubusercontent.com/pajamian/rocky-tools/repo_fix/migrate2rocky/migrate2rocky.sh

Thanks

**Comment by nofateyang** [comment]
> Can you try this version of migrate2rocky please? https://raw.githubusercontent.com/pajamian/rocky-tools/repo_fix/migrate2rocky/migrate2rocky.sh
> 
> Thanks

BAD.....

[root@svr1 ~]# ./pajamian_rocky-tools_repo_fix_migrate2rocky_migrate2rocky.sh  -r
migrate2rocky - Begin logging at Sat 26 Feb 2022 04:12:36 PM CST.


Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

Determining repository names for CentOS Linux 8......

Found the following repositories which map from CentOS Linux 8 to Rocky Linux 8:
CentOS Linux 8  Rocky Linux 8
AppStream       appstream
base            baseos
extras          extras

Getting system package names for CentOS Linux 8........Error: No Matches found

Can't get package that provides /etc/yum.repos.d/CentOS-Base.repo.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log

**Comment by pajamian** [comment]
It looks like the fix worked, but you have a .repo file which contains all your system packages but it doesn't actually belong to a package itself (ie: centos-linux-repos).  This is an edge case that migrate2rocky currently doesn't allow for, but it can be made to work (and it looks like I'm going to have to figure out a way to get migrate2rocky to recognize it and work with it).  For starters let's verify the issue, what's the output of:
```
rpm -qf /etc/yum.repos.d/CentOS-Base.repo
echo "==========================="
rpm -qa centos\*
```

**Comment by nofateyang** [comment]
> It looks like the fix worked, but you have a .repo file which contains all your system packages but it doesn't actually belong to a package itself (ie: centos-linux-repos). This is an edge case that migrate2rocky currently doesn't allow for, but it can be made to work (and it looks like I'm going to have to figure out a way to get migrate2rocky to recognize it and work with it). For starters let's verify the issue, what's the output of:
> 
> ```
> rpm -qf /etc/yum.repos.d/CentOS-Base.repo
> echo "==========================="
> rpm -qa centos\*
> ```

[root@svr1 ~]# ls /etc/yum.repos.d/
CentOS-Base.repo  epel-modular.repo  epel.repo  epel-testing-modular.repo  epel-testing.repo  nux-dextop.repo
[root@svr1 ~]# cd /etc/yum.repos.d/
[root@svr1 yum.repos.d]# rpm -qa CentOS-Base.repo
[root@svr1 yum.repos.d]# rpm -qa centos\*
centos-logos-85.8-2.el8.x86_64
centos-linux-repos-8-3.el8.noarch
centos-linux-release-8.5-1.2111.el8.noarch
centos-gpg-keys-8-3.el8.noarch
[root@svr1 yum.repos.d]#

**Comment by pajamian** [comment]
> [root@svr1 yum.repos.d]# rpm -qa CentOS-Base.repo 

That's `rpm -qf ...` not `-qa`.  Can you please show the output of `rpm -qf /etc/yum.repos.d/CentOS-Base.repo` as requested.

> centos-linux-repos-8-3.el8.noarch

...and can you show the output of `rpm -ql centos-linux-repos` ?

**Comment by pajamian** [comment]
> [root@svr1 yum.repos.d]# rpm -qf /etc/yum.repos.d/CentOS-Base.repo
> file /etc/yum.repos.d/CentOS-Base.repo is not owned by any package

This is what I thought.

> [root@svr1 yum.repos.d]# rpm -ql centos-linux-repos
...
> /etc/yum.repos.d/CentOS-Linux-AppStream.repo
> /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
> /etc/yum.repos.d/CentOS-Linux-ContinuousRelease.repo
> /etc/yum.repos.d/CentOS-Linux-Debuginfo.repo
> /etc/yum.repos.d/CentOS-Linux-Devel.repo
> /etc/yum.repos.d/CentOS-Linux-Extras.repo
> /etc/yum.repos.d/CentOS-Linux-FastTrack.repo
> /etc/yum.repos.d/CentOS-Linux-HighAvailability.repo
> /etc/yum.repos.d/CentOS-Linux-Media.repo
> /etc/yum.repos.d/CentOS-Linux-Plus.repo
> /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
> /etc/yum.repos.d/CentOS-Linux-Sources.repo
...
None of the above .repo files exist on your system, and the file that contains your system repos is the wrong file.  This falls under the following warning:

https://github.com/rocky-linux/rocky-tools/blob/main/migrate2rocky/README.md#custom-replacements-of-default-repositories

`Any distribution that has had its core repositories altered, removed, duplicated or overridden may cause migrate2rocky to break or corrupt the system when run. Any attempt to migrate such systems, even after reversing the changes made by such software, is not supported in any way.`

...my suggestion:
```
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.DISABLED
dnf --disablerepo=\* reinstall https://dl.rockylinux.org/vault/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-linux-repos-8-3.el8.noarch.rpm
```
Then run the new copy of migrate2rocky that I shared with you.

**Comment by nofateyang** [comment]
> ...my suggestion:
> 
> ```
> mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.DISABLED
> dnf --disablerepo=\* reinstall https://dl.rockylinux.org/vault/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-linux-repos-8-3.el8.noarch.rpm
> ```
> 
> Then run the new copy of migrate2rocky that I shared with you.

It works!!!
Now is upgrading and reinstall 1659 packages, waiting for final result.
