### ISSUE TITLE
Help with prerequisite CentOS 8.5

### ISSUE THREAD

**Issue by mrbaseman** [rocky-linux/rocky-tools#172]
Hi,

I wanted to migrate CentOS installations of a couple of VMs which were powered off some time. They were still on CentOS 8.4 and an update to 8.5 failed because of the EOL of CentOS.
I came across this blog, which helped me to solve the problem:

https://techglimpse.com/failed-metadata-repo-appstream-centos-8/

Maybe it referring to it helps others to solve the same problem more quickly. 

Cheers, Martin

**Comment by pajamian** [comment]
migrate2rocky accounts for this by changing the repourls to point to the CentOS Linux 8.5 vault mirror that we maintain.  If you're getting an error that is fixed by updating from CentOS vault then that is likely a bug in migrate2rocky.  Can you supply the migrate2rocky.log file from the failed migration so that I can review it and see if there's something I can do to fix the issue?

**Comment by mrbaseman** [comment]
The problem was not during running `migrate2rocky`. 

I have assumed that I shall update the Centos installation to 8.5 before running the migration script. The first item [in the documentation](https://docs.rockylinux.org/guides/migrate2rocky/) "CentOS Stream, CentOS, Alma Linux, RHEL, or Oracle Linux running well on a hardware server or VPS. The current supported version for each of these is 8.5." has made me believe this. 

Actually, a bit further down, this documentation instructs the reader to "check out migrate2rocky's README page". 
I must admit that I haven't checked this [README.md](https://github.com/rocky-linux/rocky-tools/tree/main/migrate2rocky) carefully enough, because at a second look, I find similar instructions to the ones that I was suggesting in the current issue  in the [EL 8.0 migration section of the README.md](https://github.com/rocky-linux/rocky-tools/tree/main/migrate2rocky#el80-migrations)

I'll close this issue. Anyhow, feel free to take away the message that EOL of CentOS has made the migration a bit more complicated, and improving  [the documentation](https://docs.rockylinux.org/guides/migrate2rocky/) in this aspect might help users to migrate their systems. 

(probably the repository of the rocky-tools is the wrong place to report this)
