### ISSUE TITLE
distro-sync requires --nobest

### ISSUE THREAD

**Issue by MilanKerslager** [rocky-linux/rocky-tools#173]
migrate2rocky.log did not finish. I had to add --nobest to proceed (dnf distro-sync)
This was not sufficient to proceed: dnf distro-syn --skip-broken
This worked: dnf distro-syn --skip-broken --nobest

Output from /var/log/migrate2rocky.log:
Error:
 Problem 1: cannot install the best update candidate for package libreport-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
 Problem 2: package python3-libreport-2.9.5-15.el8.rocky.6.0.x86_64 requires libreport = 2.9.5-15.el8.rocky.6.0, but none of the providers can be installed
  - cannot install the best update candidate for package python3-libreport-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.i686
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
 Problem 3: package libreport-web-2.9.5-15.el8.rocky.6.0.x86_64 requires libreport = 2.9.5-15.el8.rocky.6.0, but none of the providers can be installed
  - cannot install the best update candidate for package libreport-web-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.i686
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
 Problem 4: package libreport-plugin-ureport-2.9.5-15.el8.rocky.6.0.x86_64 requires libreport = 2.9.5-15.el8.rocky.6.0, but none of the providers can be installed
  - cannot install the best update candidate for package libreport-plugin-ureport-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.i686
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
 Problem 5: package libreport-plugin-mailx-2.9.5-15.el8.rocky.6.0.x86_64 requires libreport = 2.9.5-15.el8.rocky.6.0, but none of the providers can be installed
  - cannot install the best update candidate for package libreport-plugin-mailx-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.i686
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
 Problem 6: package libreport-cli-2.9.5-15.el8.rocky.6.0.x86_64 requires libreport = 2.9.5-15.el8.rocky.6.0, but none of the providers can be installed
  - cannot install the best update candidate for package libreport-cli-2.9.5-15.el8.x86_64
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.i686
  - nothing provides libreport-filesystem = 2.9.5-15.el8.rocky.6.0 needed by libreport-2.9.5-15.el8.rocky.6.0.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by nazunalika** [comment]
Thank you for the report! We have a fix coming in to address this.

**Comment by nazunalika** [comment]
Fixed packages should be in mirrors now.
