### ISSUE TITLE
Not able to install kernel-4.18.0-348.20.1.el8_5.x86_64

### ISSUE THREAD

**Issue by alpana17** [rocky-linux/rocky-tools#185]
I have launched an EC2 instance with 4.18.0-305.3.1.el8_4.x86_64 kernel on rocky linux 8
Now I am trying to install specific kernel version by cmd [yum install kernel-4.18.0-348.20.1.el8_5.x86_64]
but it says:  No match for argument: kernel-4.18.0-348.20.1.el8_5.x86_64
![image](https://user-images.githubusercontent.com/8611615/181205851-351a1410-d1d9-48ea-8533-b9d6baab3b12.png)

How can I install required package

**Comment by pajamian** [comment]
This is help for the Rocky Tools utilities.  You want general Rocky Linux support which you can get from one of the following:
[The Rocky Linux Form](https://forums.rockylinux.org/)
[The Rocky Linux Mailing List](https://lists.resf.org/mailman3/lists/rocky.lists.resf.org/)
[Rocky Linux IRC Chat on the LiberaChat network](https://wiki.rockylinux.org/irc/)
[Rocky Linux MatterMost Chat](https://chat.rockylinux.org/)

...please direct your question to one of the above.
