### ISSUE TITLE
Package naming convention is not followed for mod_ssl

### ISSUE THREAD

**Issue by SHAHIDNX** [rocky-linux/rocky-tools#189]
Standard linux package follows the naming convention as mod-ssl (with hyphen between) but in rocky linux it is declared as mod_ssl (with underscore).  

In Centos 7 too this package is mod-ssl ( with hyphen which is correct).

Fix : change package name from mod_ssl to mod-ssl

[root@abc/]# yum -y install mod-ssl
Last metadata expiration check: 0:01:22 ago on Sun Oct  2 09:35:33 2022.
No match for argument: mod-ssl
Error: Unable to find a match: mod-ssl

**Comment by pajamian** [comment]
This forum is for support for the rocky-tools utilities.  For general Rocky Linux support please choose one of the options under the community tab at https://rockylinux.org/.

That said, Rocky Linux is a rebuild of Red Hat Enterprise Linux, and as such we use the same package names as Red Hat.  Red Hat Enterprise Linux uses mod_ssl for the package name, and so if you believe it should be changed you should contact Red Hat support and get them to change it.

**Comment by themsley-voiceflex** [comment]
[root@centos7 ~]# rpm -q mod_ssl
mod_ssl-2.4.6-97.el7.centos.5.x86_64
