### ISSUE TITLE
Docs say migration is supported from CentOS Stream 8.5 - what about CentOS Stream 8.6?

### ISSUE THREAD

**Issue by srfn8kd** [rocky-linux/rocky-tools#191]
Is the migration script compatible for migrating from CentOS Stream 8.6?  I seem to see several hard coded lines in the script that signify 8.5

Thanks!

**Comment by pajamian** [comment]
It should work fine with newer versions of CentOS Stream but as always please be sure to backup your system and test the migration (if you can) before performing it on a production machine.

The hard-coded lines with 8.5 have to do with migrating from CentOS Linux 8 which went EOL at version 8.5 and are not used for CentOS Stream 8 migrations.

**Comment by srfn8kd** [comment]
Thank you Peter, appreciated!
