### ISSUE TITLE
Rocky8.7 gnome-boxes crash when clicking on "Create a Virtual Machine"

### ISSUE THREAD

**Issue by takist** [rocky-linux/rocky-tools#195]
Latest updates installed, when i click in create a new virtual machine crashes immediately and exits, in logs says 
`(gnome-boxes): CRITICAL : osinfo_list_get_nth: assertion 'list->priv->array->len > idx' failed`

**Comment by nazunalika** [comment]
This repo is primary for scripts and utilities for mirrors or rocky migrations.

You may want to ask this question at our [forums](https://forums.rockylinux.org) or [chat](https://chat.rockylinux.org). If you are sure it is a bug, you can report it to our [bug tracker](https://bugs.rockylinux.org).
