### ISSUE TITLE
Getting more info about potential conflicts

### ISSUE THREAD

**Issue by dreddpenguin** [rocky-linux/rocky-tools#2]
Attempting to run script on freshly installed CentOS 8.3, minimal install
Physical install on server hardware, getting the following

```
# ./centos2rocky.sh
Ensuring rpm, yum, and curl are here.
Ensuring your version of CentOS is supported
Finding our modules that are enabled
There are some modules that are unsure of how to handle. This normally shouldn't happen. Do you want to resolve this yourself (Yes) or continue (No)?
```

Reviewing script options and code I'm not sure how to determine which modules are in question.

**Comment by nazunalika** [comment]
This should be hopefully fixed in the latest iteration of the script. Can you please see if it reports back module names for you?

**Comment by pajamian** [comment]
centos2rocky has been deprecated in favor of migrate2rocky.  Please try again with migrate2rocky and see if your issue has been resolved.

**Comment by NeilHanlon** [comment]
@dreddpenguin please give this a try with the new script and feel free to re open the issue if you encounter trouble! thank you for your report
