### ISSUE TITLE
Failed Migration tor Rocky: Found a full or partial RockyLinux install already in place

### ISSUE THREAD

**Issue by marseaplage** [rocky-linux/rocky-tools#203]
I am trying to migrate from centos 8.5.2111 to Rocky 8 by using the script: https://raw.githubusercontent.com/rocky-linux/rocky-tools/main/migrate2rocky/migrate2rocky.sh but I got this error:

`migrate2rocky - Begin logging at dom 16 jul 2023 21:14:43 -05.

Removing dnf cache
Preparing to migrate CentOS Linux 8 to Rocky Linux 8.

Determining repository names for CentOS Linux 8......

Found the following repositories which map from CentOS Linux 8 to Rocky Linux 8:
CentOS Linux 8 Rocky Linux 8
appstream appstream
baseos baseos
extras extras

Getting system package names for CentOS Linux 8
Found a full or partial RockyLinux install already in place. Aborting

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

A log of this installation can be found at /var/log/migrate2rocky.log`

Actually I applied all these steps to try to solve the issue, as is mentioned in https://docs.linuxfabrik.ch/operating-systems/rockylinux.html but it doesn't work, the error persists.

`cd /tmp

Example for CentOS 8.5
AppStream:
wget http://vault.centos.org/centos/8.5.2111/AppStream/x86_64/os/Packages/centos-backgrounds-85.8-2.el8.noarch.rpm
wget http://vault.centos.org/centos/8.5.2111/AppStream/x86_64/os/Packages/centos-logos-ipa-85.8-2.el8.noarch.rpm

BaseOS:
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-gpg-keys-8-3.el8.noarch.rpm
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-indexhtml-8.0-0.el8.noarch.rpm
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-linux-release-8.5-1.2111.el8.noarch.rpm
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-linux-repos-8-3.el8.noarch.rpm
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-logos-85.8-2.el8.x86_64.rpm
wget http://vault.centos.org/centos/8.5.2111/BaseOS/x86_64/os/Packages/centos-logos-httpd-85.8-2.el8.noarch.rpm

rpm -Uvh --force centos-*.rpm

this removes all rocky stuff:
dnf -y remove rocky-gpg-keys

rm -f /etc/yum.repos.d/Rocky*
dnf clean all`

Could you help me please?

**Comment by pajamian** [comment]
This error happens when you attempt to run migrate2rocky a second time on a migration that already failed.  migrate2rocky is refusing to run again because your system is already damaged from the first migration attempt and a further attempt can only result in additional damage.

migrate2rocky keeps a certain number of old logs, the real error will be from the initial attempt, in the oldest migrate2rocky.log file (possibly migrate2rocky.log.1)

**Comment by pajamian** [comment]
> Actually I applied all these steps to try to solve the issue, as is mentioned in https://docs.linuxfabrik.ch/operating-systems/rockylinux.html but it doesn't work, the error persists.

Oh and this is really bad advice to have followed.  You've likely made the situation much worse on your system by following this advice.

**Comment by pajamian** [comment]
I'll re-iterate what was said in the chat.  You attempted to update from CentOS 7 following the advice of a random post on the internet.  This action is unsupported and in your case resulted in a partially updated system that later caused migrate2rocky to fail.  There is no telling what other damage is left on the system from the previous upgrade or the resulting failed migration which will likely come back to cause issues at some point down the road.  Such upgrades and the systems that result from them are not supported by Rocky Linux or the migrate2rocky tool.  You are encouraged to create a new clean install of Rocky Linux 8 or 9 and then copy your programs, settings and data over to that, this will result in the cleanest, best possible experience going forward.
