### ISSUE TITLE
Fedora stable (actual 39) migrate to Rocky Linux  ?

### ISSUE THREAD

**Issue by amidevous** [rocky-linux/rocky-tools#209]
How to migrate to Rocky Linux from CentOS Stream, CentOS, Alma Linux, RHEL, or Oracle Linux

https://docs.rockylinux.org/guides/migrate2rocky/

ok and if they and on Fedora did how?

you have to think about all the distributions please thank you

**Comment by pajamian** [comment]
Migration from Fedora and other non-RHEL derived distros is not supported.  migrate2rocky only supports migration from EL distributions of the same major release.

**Comment by amidevous** [comment]
them it's wrong stop all rpm distributions originally from rhel
so false stop saying that it doesn't come from rhel because it's false
it was rhel who created the rpm system
it's just that Fedora are making more progress in their development, that's all
It's up to you to adapt, uninstall or install the version of the necessary packages accordingly, it's all
on deb package-based distributions you can migrate from any distribution that uses deb packages to any distribution that uses the deb package system
you can migrate Ubuntu/Debian
or Debian/Kali Linux
Raspbian/Ubuntu etc.

so it must be the same on rpm distributions

it's up to you to do what is necessary so that your tools uninstall or install the packages in their necessary version and that's all
