### ISSUE TITLE
Migration from Fedora and other non-RHEL derived distros is not supported.  migrate2rocky only supports migration from EL distributions of the same major release.

### ISSUE THREAD

**Issue by amidevous** [rocky-linux/rocky-tools#210]
Migration from Fedora and other non-RHEL derived distros is not supported.  migrate2rocky only supports migration from EL distributions of the same major release.

_Originally posted by @pajamian in https://github.com/rocky-linux/rocky-tools/issues/209#issuecomment-1936964495_
            
and what's more, you allow yourself to close so you're talking bullshit

It is up to the one who opens an issue to say if it is resolved and can be closed or not.

them it's wrong stop all rpm distributions originally from rhel
so false stop saying that it doesn't come from rhel because it's false
it was rhel who created the rpm system
it's just that Fedora are making more progress in their development, that's all
It's up to you to adapt, uninstall or install the version of the necessary packages accordingly, it's all
on deb package-based distributions you can migrate from any distribution that uses deb packages to any distribution that uses the deb package system
you can migrate Ubuntu/Debian
or Debian/Kali Linux
Raspbian/Ubuntu etc.

so it must be the same on rpm distributions

it's up to you to do what is necessary so that your tools uninstall or install the packages in their necessary version and that's all

I'm asking how to migrate from Fédora, that's all

and if you don't know and you don't answer and you those who have the answer answer and that's all

it is only when the necessary response is given and I have confirmed that it works that the issue can be closed and not before

**Comment by pajamian** [comment]
This topic is closed.  Do not open further issues on this topic.
