### ISSUE TITLE
Migration Failed Over SSH from CentOS 8.5 - computer keeps restarting in BIOS with "Boot Option Restoration" and reboot timer

### ISSUE THREAD

**Issue by brarharry** [rocky-linux/rocky-tools#212]
Migration scripts completes with no errors on local computer:

```
Adding boot menu entry for EFI firmware configuration
done
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0003,0000,0002,0001
Boot0000* CentOS Linux
Boot0001* UEFI: Built-in EFI Shell
Boot0002* UEFI OS
Boot0003* Rocky Linux

Done, please reboot your system.
A log of this installation can be found at /var/log/migrate2rocky.log
``` 

But keeps rebooting with in BIOS with a blue screen "Boot Option Restoration" until I manually select "Always Continue Boot".

I would be upgrading servers remotely via SSH and using this script and would not be able to enter the BIOS remotely. Has anyone experienced this?

**Comment by pajamian** [comment]
Can you share your migrate2rocky.log file?

**Comment by brarharry** [comment]
[migrate2rocky.txt](https://github.com/rocky-linux/rocky-tools/files/14455744/migrate2rocky.txt)

**Comment by pajamian** [comment]
I can't find anything of concern in your logs, so I would say that there is something else that needs to be done in addition to the normal steps taken to fix up the EFI boot by migrate2rocky.

Can you take a copy of the blue screen you're getting from your BIOS?  I'd like to see exactly what it's saying.

**Comment by brarharry** [comment]
When I checked BIOS settings, the boot order was set to prioritize “UEFI OS”. 
Not sure if there is a way to set the boot order if you are trying to upgrade an iot device remotely from Centos 8.5 to RockyLinux 8 via SSH.

**Comment by pajamian** [comment]
Not sure either, as a security issue it may require physical access to the machine or at least some sort of ikvm solution to change the BIOS boot order.  I'd like to know if you find a solution that works, though, as I might be able to include it at least in the README docs for migrate2rocky if not in the script itself.
