### ISSUE TITLE
Migrate from Operating System: CentOS Linux 7 (Core)  to Rocky 8.

### ISSUE THREAD

**Issue by Hec-gitHub** [rocky-linux/rocky-tools#213]
OS environment before upgrade:
Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.el7.x86_64
      Architecture: x86-64
      
 Can I smoothly migrate to Rocky 8 using script migrate2rocky.sh

**Comment by nazunalika** [comment]
Hello. migrate2rocky.sh is for any enterprise linux 8 to rocky linux 8 and migrate2rocky9.sh is for 9. The [readme](https://github.com/rocky-linux/rocky-tools/tree/main/migrate2rocky) briefly touches on this. These scripts do not perform upgrades.

If you are wanting to go to Rocky Linux 8, you are recommended to install a new system and migrate your data that way. You can also use a tool called "ELevate" but we do not formally support it.
