### ISSUE TITLE
How do we can migrate from CentOS-7.x to RockLinux-8.x

### ISSUE THREAD

**Issue by adrianovieira** [rocky-linux/rocky-tools#30]
Hi!

Thanks by your great job.

We would like to migrate our current servers from CEntOS-7.x to  RockLinux-8.x.

Please, what's the best way to accomplish this?

**Comment by nazunalika** [comment]
I would recommend that you perform backups, install a brand new 8 system, and restore as necessary (taking into account configuration changes). That would be the best way to migrate between major releases.

**Comment by pajamian** [comment]
a migration or upgrade from any EL7 to RockyLinux 8 is not supported.  You need to do as nazunlika said and install RockyLinux 8 fresh.
