### ISSUE TITLE
redhat-logos-httpd should be replaced with rocky-logos-httpd

### ISSUE THREAD

**Issue by vchepkov** [rocky-linux/rocky-tools#39]
migration script leaves orphaned redhat-logos-httpd package, it should be replaced with rocky-logos-httpd

**Comment by robert-scheck** [comment]
I experienced the same (coming from CentOS rather from RHEL), thus I proposed #43

**Comment by pajamian** [comment]
Thanks for the PR robert-scheck.  It looks good to me.

**Comment by pajamian** [comment]
This is done now, thanks again.
