### ISSUE TITLE
suggest to remove dnf-plugin-subscription-manager

### ISSUE THREAD

**Issue by vchepkov** [rocky-linux/rocky-tools#40]
migration script suggests removing subscription-manager, but not dnf-plugin-subscription-manager
After subscription-manager is removed, the following warnings are produced 
```
Failed loading plugin "upload-profile": cannot import name 'packageprofilelib'
Failed loading plugin "subscription-manager": cannot import name 'injection'
Failed loading plugin "product-id": No module named 'subscription_manager.productid'
```

They are solved by removing dnf-plugin-subscription-manager

**Comment by pajamian** [comment]
Thanks, that's a good idea, I'll make that change.

**Comment by pajamian** [comment]
vchepkov: Have a look at PR #48 and let me know if it looks good to you.

**Comment by vchepkov** [comment]
Looks good, thank you

**Comment by pajamian** [comment]
Okay, merged.
