### ISSUE TITLE
springdale-logos-httpd should be replaced with rocky-logos-httpd

### ISSUE THREAD

**Issue by Hydranet** [rocky-linux/rocky-tools#42]
I migrated my systems using the migration script and it worked without any problems, but there was only one Springdale Linux 8 package that the script didn't catch. The package that was still left installed was springdale-logos-httpd, which I removed and then reinstalled the Rocky Linux equivalent:
1. rpm -e --nodeps springdale-logos-httpd
2. yum install rocky-logos-httpd

**Comment by robert-scheck** [comment]
I experienced the same (coming from CentOS rather from Springdale), thus I proposed #43
