### ISSUE TITLE
An error occurred while we were attempting to convert your system to Rocky Linux.

### ISSUE THREAD

**Issue by lehronn** [rocky-linux/rocky-tools#44]
Commandline error:
Syncing packages

Last metadata expiration check: 0:00:09 ago on Wed 23 Jun 2021 02:14:52 PM CEST.
Error: 
 Problem 1: package python3-pip-9.0.3-19.el8.noarch requires platform-python-pip = 9.0.3-19.el8, but none of the providers can be installed
  - cannot install the best update candidate for package python3-pip-9.0.3-19.el8.noarch
  - platform-python-pip-9.0.3-19.el8.noarch does not belong to a distupgrade repository
 Problem 2: package python3-pip-9.0.3-19.el8.noarch requires platform-python-pip = 9.0.3-19.el8, but none of the providers can be installed
  - cannot install both platform-python-pip-9.0.3-19.el8.rocky.noarch and platform-python-pip-9.0.3-19.el8.noarch
  - problem with installed package python3-pip-9.0.3-19.el8.noarch
  - cannot install the best update candidate for package platform-python-pip-9.0.3-19.el8.noarch
  - python3-pip-9.0.3-19.el8.noarch does not belong to a distupgrade repository
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Error during distro-sync.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log

**Comment by johna77** [comment]
Hi @lehronn,
Those modules are blacklisted when you distro-sync or you manually remove packages with `yum remove python3-pip-9.0.3-19.el8.noarch`. 
you can try `dnf module list` after you found python-pip module, remove manually `dnf reset `package name(which you want to remove those blacklisted package)` | `dnf remove "python3-pip-9.0.3-19.el8.noarch"` . 
Now try to find same package from dnf module list.
I hope it will work.

**Comment by lehronn** [comment]
hello, heap i traied remove that package but when i saw 20 dependenties to remove.... i was done here.
after reboot system doest start. i have emergency mode ;/

**Comment by pajamian** [comment]
What distro are you migrating from?  This looks like an issue from a mirror not being synced properly.

**Comment by lehronn** [comment]
that was been centoos 8.4.

what is more: after fresh installation stable rocky linux i cannot install ansible because i received the same issue with that package (platform-python-pip and python 36-3.6-8.

**Comment by pajamian** [comment]
Can you please post the full migrate.rocky.log file?  Also post the full command you use when trying to install ansible and the full results, please.

**Comment by pajamian** [comment]
Closing due to lack of information.
