### ISSUE TITLE
Failed loading modules from CentOS8 to Rocky Linux 

### ISSUE THREAD

**Issue by akoundal** [rocky-linux/rocky-tools#45]
not able to convert the centOS 8 machine to rocky. 
Getting these errors: 

![image](https://user-images.githubusercontent.com/19417434/123152943-01d66c80-d41a-11eb-9dab-4406856bbc7e.png)

this keeps on repeating even though it tries to find the repos. 
![image](https://user-images.githubusercontent.com/19417434/123153083-27637600-d41a-11eb-9df8-8815ef10e98e.png)

This is the failure. 
![image](https://user-images.githubusercontent.com/19417434/123153178-3ea26380-d41a-11eb-9703-a7fd404520e7.png)

there is nothing more in the logs then the uploaded information. Looking forward to have a fix so that can migrate asap.

**Comment by akoundal** [comment]
After reboot and running the script again I am on ROCKY linux. CHeers!!!!

**Comment by pajamian** [comment]
Cool, sounds like yo had a networking issue.

**Comment by NeilHanlon** [comment]
glad it worked out!
