### ISSUE TITLE
EFI entry added points to incorrect partition

### ISSUE THREAD

**Issue by McNutnut** [rocky-linux/rocky-tools#49]
After migration from CentOS 8 to Rocky Linux 8 on a UEFI system, the new EFI entry can be incorrectly created if the EFI partition isn't the first partition on the disk. 

[The call to `efibootmgr` in `fix_efi()`](https://github.com/rocky-linux/rocky-tools/blob/aba39dd2944ede0536a571eb7e7e0f8d4ce91d0d/migrate2rocky/migrate2rocky.sh#L776) does not include the `-p` parameter to indicate the partition on the disk.  By default, the first partition is used (default value of `-p` is `1`)

`efibootmgr -c -d "$efi_mount" -L "Rocky Linux" -l /EFI/rocky/grubx64.efi`
should be something such as
`efibootmgr -c -d "$efi_disk" -p "$efi_disk_part" -L "Rocky Linux" -l /EFI/rocky/grubx64.efi`

Ex,
`efibootmgr -c -d /dev/sda -p 2 -L "Rocky Linux" -l /EFI/rocky/grubx64.efi`
instead of
`efibootmgr -c -d /dev/sda2 -L "Rocky Linux" -l /EFI/rocky/grubx64.efi`

**Comment by pajamian** [comment]
Can you test with PR #52 and see if it works for you?

**Comment by pajamian** [comment]
Fixed and pulled.

**Comment by McNutnut** [comment]
Thank you! Works great!
