### ISSUE TITLE
script to convert from CentOS or Oracle Linux to Rocky Linux

### ISSUE THREAD

**Issue by shikari7** [rocky-linux/rocky-tools#5]
Can we get a script to convert to Rocky Linux once it's released? After the CentOS announcement, I ran this script:

https://github.com/oracle/centos2ol

to convert to Oracle Linux but I would much rather be on Rocky Linux than Oracle if possible. 

Let me know how I can help. 👍

**Comment by nazunalika** [comment]
A conversion script is in this repo. It is only for CentOS to Rocky. In the future we will design the script to work with other EL systems.
