### ISSUE TITLE
minor "errors" in the script?

### ISSUE THREAD

**Issue by dv8472** [rocky-linux/rocky-tools#59]
Script lines:
32) Rocky ain't RC anymore.
43) BASH_VERSINFO is missing the $ for a variable
49) EUID is missing the $ for a variable

**Comment by pajamian** [comment]
> Script lines:
> 32) Rocky ain't RC anymore.

Thanks I'll fix that.

> 43) BASH_VERSINFO is missing the $ for a variable
> 49) EUID is missing the $ for a variable

The "$" is not required inside (( ... )).

**Comment by pajamian** [comment]
Fixed, pulled, merged.
