### ISSUE TITLE
Allow migrate to proceed when /sys not mounted

### ISSUE THREAD

**Issue by bcomisky** [rocky-linux/rocky-tools#61]
I was updating a container system in a chroot that didn't have /sys mounted and had to comment out this block in order for it to proceed.  

```bash
    # Check if we have /sys mounted and it is looking sane
    if ! [[ -d /sys/class/block ]]; then
         exit_message "/sys is not accessible."
    fi
```
It looks like /sys is only used for efi updating, and the the /sys/firmware/efi check just below this block seems to be sufficient for that.

Or, if the update_efi boolean could be dependent on both /sys/class/block and and /sys/firmware/efi existing if it is important.

**Comment by electroniceel** [comment]
Requiring /sys being mounted for the efi check is just a small thing. If it were just that, we could just print out a warning.

The much bigger issue is that you are then running a distupgrade with the scriptlets of all RPMs without having /sys available. Some scriptlets configure default configuration based on the hardware or configuration they find during %post. They rely on /dev, /proc and /sys being available. They could fail silently or do the wrong thing and you won't immediately notice. I regularly install RPMs in a chroot environment for an imaging system at work. And I noticed that having /dev, /proc and /sys available is a must for reliable operation.

The solution for a chroot is to bind-mount /dev, /proc and /sys into the chroot environment.

We could improve migrate2rocky to also check for /dev and /proc and print a error message suggesting the bind mount.

**Comment by bcomisky** [comment]
That makes sense, I probably have an edge case here.

**Comment by pajamian** [comment]
> Requiring /sys being mounted for the efi check is just a small thing. If it were just that, we could just print out a warning.

We could do that, although a warning is not going to help much if we then go on to perform the migration without giving the user a chance to act on it.

> The much bigger issue is that you are then running a distupgrade with the scriptlets of all RPMs without having /sys available. Some scriptlets configure default configuration based on the hardware or configuration they find during %post. They rely on /dev, /proc and /sys being available.

Presumably, though, he's already installed all those RPMs and it wasn't negatively affected by the lack of /sys, a migration should not further damage the system any more than it was at the initial install stage.

> The solution for a chroot is to bind-mount /dev, /proc and /sys into the chroot environment.

The issue I see here is that when we check /sys for EFI support it will be seen to have it and migrate2rocky will then falsely attempt to fix the EFI on the chroot.  If we're going to advocate for such a method for migrating a chroot then we need to find a different method of detecting whether the system uses EFI and secure boot.

> We could improve migrate2rocky to also check for /dev and /proc and print a error message suggesting the bind mount.

**Comment by pajamian** [comment]
(I'm reopening this issue for now because I think this bears some further discussion)

**Comment by pajamian** [comment]
Closing again, due to no further comments.
