### ISSUE TITLE
Add support to satellite registered systems

### ISSUE THREAD

**Issue by cruwer** [rocky-linux/rocky-tools#62]
Hi, could you please add some options to migrate systems that are registered to the Red Hat Satellite product?

**Comment by pajamian** [comment]
Please see https://github.com/rocky-linux/rocky-tools/blob/main/migrate2rocky/README.md#custom-replacements-of-default-repositories for why we don't support migrations for satellite at this time.  I m open to suggestions on how we can resolve those issues, though.

**Comment by pajamian** [comment]
Closing due to no further comments.

**Comment by ccandreva** [comment]
If Rocky is already in the Satellite or Foreman / Katello system, the user could specifiy their own map of their Centos repo names to their Rocky repo names. A bit of an advanced option, but better than nothing, and once tested can be read from an include file.
