### ISSUE TITLE
using in LXC container  cent8 to rocky fails immediately

### ISSUE THREAD

**Issue by tastle73** [rocky-linux/rocky-tools#74]
this is the error:  

Can't find EFI mount.  No EFI  boot detected.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

**Comment by pajamian** [comment]
Can you please show the /var/log/migrate2rocky.log file?

**Comment by tastle73** [comment]
that's all there is in there

**Comment by pajamian** [comment]
If you can't show the entire migrate2rocky.log file then I can't help you, there is certainly much more in it than what you have shared.

**Comment by tastle73** [comment]
I agree with that, there's actually nothing else in there, I assume from running it over and over.  would running the script 'set -x' be helpful?  I  can also just stand up a fresh centos8 container and see what happens with that.

**Comment by pajamian** [comment]
What is the command you're using to run migrate2rocky?

**Comment by tryano** [comment]
Same problem here. 

cat /var/log/migrate2rocky.log
Can't find EFI mount. No EFI boot detected.

My command was: ./migrate2rocky.sh -r

**Comment by tastle73** [comment]
> What is the command you're using to run migrate2rocky?

migrate2rocky.sh -r

**Comment by pajamian** [comment]
Okay, yes, can you add set -x to the top of the script and show the output?

**Comment by andrin55** [comment]
Same issue here. It fails after not finding /boot/efi:
```
+ local efi_mount kname
+ declare -g -a efi_disk efi_partition
++ findmnt --mountpoint /boot/efi --output SOURCE --noheadings
+ efi_mount=
+ exit_message 'Can'\''t find EFI mount.  No EFI  boot detected.'
+ errmsg '
Can'\''t find EFI mount.  No EFI  boot detected.

'
+ local msg
+ msg_format msg '
Can'\''t find EFI mount.  No EFI  boot detected.

'
+ local _var
+ _var=msg
+ shift
+ ((  1 > 1  ))

Can't find EFI mount.  No EFI  boot detected.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log
```

**Comment by pajamian** [comment]
I think I see what's happening here.  Does LXC bind mount /sys from the host system?  I think what is happening is the host system is EFI mounted so the /sys which is bind-mounted and a copy of the one on the host is showing that EFI boot exists, but the container itself doesn't do EFI boot, and can't access the EFI partition from the host.  I think that if the EFI partition isn't found then we should simply turn off EFI boot processing and allow the script to continue.

**Comment by andrin55** [comment]
Yes it is mounted from the host system including /sys/firmware/efi/. 
One possible solution would just to ignore it and carry on if no EFI partition is not mounted. But if a user has chosen to not mount the EFI partition for whatever reason the system would fail to boot. 

Another possible solution would be to check if it's running inside a container (for ex. with systemd-detect-virt). This utility is included with the main systemd package and should therefore be present on all supported operating systems.

**Comment by pajamian** [comment]
> Another possible solution would be to check if it's running inside a container (for ex. with systemd-detect-virt). This utility is included with the main systemd package and should therefore be present on all supported operating systems.

This is a good idea, I'm going with this one.

**Comment by pajamian** [comment]
@tastle73 @tryano @andrin55 can you test with this version, please:
https://github.com/pajamian/rocky-tools/tree/issue74/migrate2rocky

**Comment by andrin55** [comment]
> @tastle73 @tryano @andrin55 can you test with this version, please:
> https://github.com/pajamian/rocky-tools/tree/issue74/migrate2rocky

Thank you it worked. 

If anyone else is running an unprivileged LXC CentOS 8 container: There is a bug with the filesystem package (https://bugzilla.redhat.com/show_bug.cgi?id=1589968#c20). The workaround does not work since the /etc/rpm/macros.dist file seems to gets overwritten when running the script. In my case migration was successful when removing the exit code check on line 793 from distro-sync.

**Comment by pajamian** [comment]
> If anyone else is running an unprivileged LXC CentOS 8 container: There is a bug with the filesystem package (https://bugzilla.redhat.com/show_bug.cgi?id=1589968#c20). The workaround does not work since the /etc/rpm/macros.dist file seems to gets overwritten when running the script. In my case migration was successful when removing the exit code check on line 793 from distro-sync. Another option would be to try it with --exclude=filesystem.

That workaround should work with any file named macros.*, can you try this before running the script and see if it works:
`printf '%s\n' '%_netsharedpath /sys:/proc' > /etc/rpm/macros.migrate2rocky`

...if it works I'll incorporate it into the script.

**Comment by andrin55** [comment]
> > If anyone else is running an unprivileged LXC CentOS 8 container: There is a bug with the filesystem package (https://bugzilla.redhat.com/show_bug.cgi?id=1589968#c20). The workaround does not work since the /etc/rpm/macros.dist file seems to gets overwritten when running the script. In my case migration was successful when removing the exit code check on line 793 from distro-sync. Another option would be to try it with --exclude=filesystem.
> 
> That workaround should work with any file named macros.*, can you try this before running the script and see if it works:
> `printf '%s\n' '%_netsharedpath /sys:/proc' > /etc/rpm/macros.migrate2rocky`
> 
> ...if it works I'll incorporate it into the script.

It worked.

**Comment by pajamian** [comment]
@andrin55 can you try with this version of migrate2rocky and see if it works properly?  It should create and remove the macros file as needed for containers: https://github.com/pajamian/rocky-tools/blob/issue74/migrate2rocky/migrate2rocky.sh

**Comment by andrin55** [comment]
> @andrin55 can you try with this version of migrate2rocky and see if it works properly? It should create and remove the macros file as needed for containers: https://github.com/pajamian/rocky-tools/blob/issue74/migrate2rocky/migrate2rocky.sh

Worked flawlessly. No errors while installing, no files left in /etc/rpm/ after migration. I think this issue can be closed. Thank you for your work.

**Comment by pajamian** [comment]
Changes merged.
