### ISSUE TITLE
sha512sum fails when cURL gets HTTP 307 

### ISSUE THREAD

**Issue by blouphil** [rocky-linux/rocky-tools#77]
Using a private repository that is returning HTTP 307 on /RPM-GPG-KEY-rockyofficial, cURL does not follow the `Location: header`, creates an empty RPM-GPG-KEY-rockyofficial, then sha512sum check fails

Adding `--location` to the cURL call fixes the problem

https://github.com/rocky-linux/rocky-tools/blob/bc7a35a1e7f8630dca087b3f503475fabe7e85c6/migrate2rocky/migrate2rocky.sh#L857

**Comment by pajamian** [comment]
Fixed with PR #80 
Let me know if it works for you now.

**Comment by blouphil** [comment]
@pajamian Thanks, it fixes the issue we had.
