### ISSUE TITLE
Package is upgraded to latest CentOS, then downgraded to latest Rocky

### ISSUE THREAD

**Issue by bassjoe** [rocky-linux/rocky-tools#82]
IPA server fails to start after migration.

Much like #75 but also when migrating **from CentOS 8** (NOT stream) to Rocky, which is the primary use of the script. Also the same problem could apply to **other packages**, too:

- Package `ipa-server` is newer in CentOS 8 repo than in Rocky repo
- The `pre_update` step of the script upgrades the package to the latest version in CentOS repo by calling `dnf update`, which **also migrates the data to this version**
- Later the package (but not the data) is **downgraded** to the latest version in Rocky repo

Service `ipa` fails to start because the data is newer than the program.

My workaround was to add `--exclude ipa-server ipa-client ipa-common --nobest` to the `dnf update` in line 637. And of course starting the migration with the system NOT being updated with `dnf update`, i.e. with a package version no higher than the latest in Rocky repo.

originally installed: 4.8.7-16.module_el8.3.0+753+f535d84d
latest in centos repo: 4.9.2-4.module_el8.4.0+**846**+96522ed7
latest in rocky repo: ipa-server-4.9.2-4.module+el8.4.0+**589**+9650b94f

It would be good if the script could somehow handle this problem (at least for IPA) and not render the system unusable (until Rocky packages are updated).

I also think this is a very important issue because users of FreeIPA depend much on EL distributions.

**Comment by nazunalika** [comment]
This is expected because of how modules are handled. As such, the module numbers in the release dist tag will _always_ be different between different EL derivatives, regardless of what they are.

With that being said, once the IPA packages are done, you must run: `ipa-server-upgrade --skip-version-check`

Because this is a special edge case (especially for IPA), I cannot imagine adding logic for the above command is worth the time. That is up to @pajamian however to decide that.

**Comment by pajamian** [comment]
I think that we can document this in "known issues" so that people who read it will know to run the ipa-server-upgrade command.

**Comment by pajamian** [comment]
Added this to "known issues".

**Comment by bassjoe** [comment]
When testing the fix for #81 I now also tried the `ipa-server-upgrade --skip-version-check`, but it didn't work for me. The command failed with some Tomcat error. So I'll stick with my workaround.

**Comment by pajamian** [comment]
What was the Tomcat error you were getting?

**Comment by bassjoe** [comment]
Java not found. Maybe one needs to run the one-liner from #41 first.

    failed to discover tomcat version, default to pre-9.0.31.0, error: CalledProcessError(Command ['/usr/sbin/tomcat', 'version'] returned non-zero exit status 1: '/usr/sbin/tomcat: JAVA_HOME is not set and default java installation was not found. JAVA_HOME for system applications can be set in java.conf in /etc/java\n')
    IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.

**Comment by pajamian** [comment]
That makes sense, can you try it and see if it works?  If so I'll add an extra note to the known issues entry.

**Comment by bassjoe** [comment]
Yes, I tried it once again and the `ipa-server-upgrade` command works if the java fix has been applied before.

**Comment by pajamian** [comment]
Added note in PR #100
