### ISSUE TITLE
Remove epel-next-release when migrating from Stream

### ISSUE THREAD

**Issue by psgreco** [rocky-linux/rocky-tools#84]
A new weak dependency was added to epel-release (epel-next-release) which is installed if the system is stream. When migrating to rocky, this package should be removed (or not installed at all during pre-migration update).

This may also apply to other weak deps.

**Comment by pajamian** [comment]
hrmmmm, okay.  I think I'm going to have to special case a bunch of stuff for stream migrations, they are proving to be rather problematic.

**Comment by pajamian** [comment]
Closed with #96
