### ISSUE TITLE
GlusterFS repo is removed during migration from CentOS.

### ISSUE THREAD

**Issue by TurtleFX** [rocky-linux/rocky-tools#86]
Hello,

We are using GlusterFS on some of our machines. It is installed from CentOS Storage SIG.
I've tried migrating one of the machines using migrate2rocky.sh script.
During migration GlusterFS repository is removed and not replaced by alternative Rocky repository. Therefore migration fails due to mismatched versions of the gluster from CentOS Storage SIG and repositories of Rocky Linux.

How can I solve this? Can I leave GlusterFS repository? Or is there alternative Rocky repository, which is not installed by migration script?

A log of the migration attempt:
[migrate2rocky.log](https://github.com/rocky-linux/rocky-tools/files/6862923/migrate2rocky.log)

**Comment by pajamian** [comment]
RockyLinux does not currently have a storage sig, I would imagine that is in the works, although I'm not the right person to ask.  You can continue to use the CentOS storage sig for now, but since the -release packages for it depend on centos-release which needs to be replaced with rocky-release, you will need to install the .repo files from the packages without actually installing the packages themselves.  If you unpack the .repo files from centos-release-storage-common and centos-release-gluster9 then you should be able to re-install the packages from them.  Do be aware that when CentOS 8 goes EOL at the end of the year it is highly unlikely that they will continue to support the storage sig after that, hopefully by then there will be another solution you can use.

Please let me know if you try the above and it works for you, if so then I'll document this in the migrate2rocky README file.

**Comment by TurtleFX** [comment]
Hi,

I restored my VM from the backup and since I already had GlusterFS repository (from CentOS SIG) installed (`/etc/yum.repos.d/CentOS-Gluster-9.repo`), I made a copy of it in the same directory so it would not be removed during migration.
After that I re-run migration script and everything went fine.

Also I noticed, that there is gluster9 repository from Rocky:
https://dl.rockylinux.org/pub/rocky/8/gluster9/

Is it safe to use?

**Comment by pajamian** [comment]
I missed that when I was looking earlier.  I would say that's the intended replacement for gluster9 in the CentOS storage sig, so I would recommend using that.

**Comment by TurtleFX** [comment]
After migration I've used present Rocky repostitories as a reference and created `/etc/yum.repos.d/Rocky-gluster9.repo` :
```
# Rocky-gluster9.repo
#
# The mirrorlist system uses the connecting IP address of the client and the
# update status of each mirror to pick current mirrors that are geographically
# close to the client.  You should use this for Rocky updates unless you are
# manually picking other mirrors.
#
# If the mirrorlist does not work for you, you can try the commented out
# baseurl line instead.

[gluster9]
name=Rocky Linux $releasever - gluster9
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=gluster9-$releasever
baseurl=http://dl.rockylinux.org/$contentdir/$releasever/gluster9/$basearch/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
```
I had to use baseurl, because gluster9 repo is not in the mirrorlist.
After that I 've run update and gluster packages were updated (version in Rocky repository is newer than in CentOS SIG repository).
So far everything seems to be working.

However, can this repo be added before (or during) migration to save some hassle and time? I have some other servers which are using gluster and needs to be migrated :)

**Comment by nazunalika** [comment]
From the releng side, the gluster repositories are not currently supported nor actually open to the public at this time. If you are finding gluster9 available, it is likely a mistake and I would advise against using it. It is not safe to use in any capacity.

Any storage SIG related repo or package will become available soon, but they will have to be in the mirror list first and a corresponding release package will come as well.

**Comment by pajamian** [comment]
Thanks @nazunalika for that info.  For the time being I'll add this to known issues.  Once the official sig repos are available I can look into fixing migrate2rocky to replace the CentOS ones with the RockyLinux ones.

**Comment by TurtleFX** [comment]
In that case I will be using gluster from CentOS SIG and refrain from migrating other machines, which have gluster installed.
Thank you both for the help and clarifications.

**Comment by pajamian** [comment]
Documented in PR #99
