### ISSUE TITLE
Rocky Appstream from mirrorlist broken?

### ISSUE THREAD

**Issue by hunter-nl** [rocky-linux/rocky-tools#89]
Errors during downloading metadata for repository 'appstream':
  - Status code: 502 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-8 (IP: 2a04:4e42:9::644)
Rocky Linux 8 - AppStream                        74  B/s | 341  B     00:04
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Status code: 502 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-8 (IP: 2a04:4e42:9::644)

**Comment by aminvakil** [comment]
Same on IPv4:
```
Errors during downloading metadata for repository 'appstream':
  - Status code: 502 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-8 (IP: 151.101.14.132)
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Status code: 502 for https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-8 (IP: 151.101.14.132)```

**Comment by aminvakil** [comment]
Got fixed for me!

**Comment by NeilHanlon** [comment]
This should be resolved now! I appreciate the patience and notification regarding the issue.
