### ISSUE TITLE
Error during distro-sync.

### ISSUE THREAD

**Issue by NikoGrano** [rocky-linux/rocky-tools#94]
Trying to convert Centos 8 to Rocky with latest script.
Server is default Centos 8 with following extra packages:

- @idm:DL1
- freeipa-server
- kexec
- htop (epel)
- fish (epel)

Logs:

```
  Running scriptlet: chrony-3.5-2.el8.x86_64                           699/1508
  Downgrading      : ipa-client-4.9.2-4.module+el8.4.0+589+9650b94f    700/1508
  Running scriptlet: ipa-client-4.9.2-4.module+el8.4.0+589+9650b94f    700/1508
  Running scriptlet: ipa-server-4.9.2-4.module+el8.4.0+589+9650b94f    701/1508
  Downgrading      : ipa-server-4.9.2-4.module+el8.4.0+589+9650b94f    701/1508
  Running scriptlet: ipa-server-4.9.2-4.module+el8.4.0+589+9650b94f    701/1508
  Reinstalling     : dracut-network-049-135.git20210121.el8.x86_64     702/1508
  Downgrading      : python3-wheel-wheel-1:0.31.1-2.module+el8.4.0+    703/1508
  Downgrading      : python3-virtualenv-15.1.0-19.module+el8.4.0+59    704/1508
  Running scriptlet: python3-virtualenv-15.1.0-19.module+el8.4.0+59    704/1508
  Reinstalling     : kexec-tools-2.0.20-46.el8_4.1.x86_64              705/1508
  Running scriptlet: kexec-tools-2.0.20-46.el8_4.1.x86_64              705/1508migrate2rocky.sh: line 646: 2453678 Killed                  dnf -y distro-sync

Error during distro-sync.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.
```

I was forced to rollback, so this server is no-longer available for further debugging. If needed I can try again the migration on copy of this server.

**Comment by pajamian** [comment]
It would help to have the full log from /var/log/migrate2rocky.log

From what you've provided I would say that the distro-sync got manually killed, possibly by some watchdog process or something?  Are you running any special security software that might be interfering?  Maybe it was an OOM issue?

**Comment by NikoGrano** [comment]
For sure not OOM, checked it. Full log is no longer available. Currently in progress of rollback.
After rollback finished, I could create clone and try reproduce this there. I will provide further details in a hour.

There isn't special software running on this server outside of listed software in my first post.

**Comment by pajamian** [comment]
Well, the snippet you provided explicitly says, "Killed" which references SIGKILL or signal #9 which cannot be trapped and certainly is not coming from migrate2rocky itself.  To verify next time you run migrate2rocky, can you change line 798 (the distro-sync line) to the following?

`dnf -y distro-sync || exit_message "Error during distro-sync: $?"`

That will confirm if it's being killed by a signal and which signal (but I suspect it's 9).

**Comment by NikoGrano** [comment]
Unable to find time to reproduce. Will re-open if I see it necessary.
